-- SHIVAM CREATES - Data Backup (Auto-generated)
-- Generated: 2026-08-03T19:55:28.778Z

-- ===== PROJECTS (13 rows) =====
DELETE FROM public.projects;

INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('a046c784-87ad-4b88-afa9-dbfcf584dd87', 'Motu patlu video ', 'motu-patlu-video', 'branding', 'Created engaging Motu Patlu-style promotional videos by combining video editing, motion graphics, sound effects, and creative storytelling. Edited short-form content for social media to promote businesses and products while maintaining an entertaining and visually appealing style.', NULL, 'mahajan caterers ', ARRAY['capcut', 'premeire pro', 'gemini', 'chatgpt']::text[], 'https://www.instagram.com/reel/Dar0n3MREAF/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/5a9bx0j58a8-1785782233274.png', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T18:40:16.425994+00:00', '2026-08-03T18:40:16.425994+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('f6c3cdbf-ba56-4a92-b8af-0c1a202bb1cb', 'Mundan Cermony Invitation Video ', 'mundan-cermony-invitation-video', 'video', 'Edited a Mundan Ceremony invitation video by organizing footage, adding smooth transitions, background music, color correction, titles, and special moments to create a memorable and professionally polished final video for the family.', NULL, 'Anshika Soni ', ARRAY['chat gpt', 'VN', 'gemini flow']::text[], 'https://www.instagram.com/reel/Dbls4achEHd/?utm_source=ig_web_button_share_sheet', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/u1kt29mngm8-1785784091868.jpeg', NULL, NULL, true, true, NULL, 0, NULL, '2026-08-03T19:00:19.99383+00:00', '2026-08-03T19:00:19.99383+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('042910a7-51f5-40ab-ad3c-207d181d6036', 'PREMIUM GENERAL STORE', 'premium-general-store', 'website', ' Developed a responsive and user-friendly website for Kathua Fresh, an online grocery store. The website showcases fresh fruits, vegetables, dairy products, groceries, and daily essentials with a clean design, intuitive navigation, and mobile-friendly layout to provide customers with a seamless shopping experience.', NULL, 'shivam gupta ', ARRAY['Next.js', 'tailwind', 'supabase', 'phone pe']::text[], 'https://www.premiumstorekathua.shop/', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/g6watjh2fhe-1785782362095.png', NULL, NULL, true, true, NULL, 0, NULL, '2026-08-03T18:05:05.496166+00:00', '2026-08-03T18:05:05.496166+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('34d9538f-95e7-467c-819f-b95d4ec82aee', 'Donation  website ', 'donations', 'website', 'Built a modern and responsive donation platform that helps users contribute to meaningful causes with ease. The website features a clean interface, campaign details, a streamlined donation experience, and mobile-friendly design to promote charitable giving and community support.', NULL, ' karan ', ARRAY['next.js', 'css tailwind', 'react native']::text[], 'https://www.premiumstorekathua.shop/donation', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/fkvi96h7r1h-1785781465562.png', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T18:25:25.26797+00:00', '2026-08-03T18:25:25.26797+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('d1692304-59bd-477f-81ca-5ca845038c58', 'rambo kathua ka sher ', 'rambo-kathua-ka-sher', 'branding', ': Edited engaging short-form videos featuring Rambo – Kathua Ka Sher, focusing on creative storytelling, smooth transitions, sound effects, color enhancement, and social media optimization. Produced entertaining content designed to increase audience engagement across digital platforms.', NULL, 'kartik. ', ARRAY['gemini', 'vn', 'capcut', 'click champ']::text[], 'https://shivamkakaal.github.io/RAMBOPORTFOLI/?mcp_token=eyJwaWQiOjMyNTMxMjksInNpZCI6MjY4ODgxNDAxLCJheCI6ImQ3MmJiYjQ4NzFjNTU2YTU1ZmU3MDljNDA5YTI2NWIwIiwidHMiOjE3ODU3ODYwNjEsImV4cCI6MTc4ODIwNTI2MX0.bxeKQuwi10eReFNziTx5n9Kbycdc0IzH11bsCHiBMk0', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/hso7af4s8tr-1785783283572.jpeg', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T18:51:40.577262+00:00', '2026-08-03T18:51:40.577262+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('ebfbb06f-8045-434b-a41f-54298d8f64a1', 'Rohit chat house ', 'rohit-chat-house', 'marketing', 'Created promotional videos for Rohit Chat House to showcase menu items, special offers, and the dining experience. Edited engaging social media content using smooth transitions, text animations, background music, and visually appealing effects to attract customers and enhance brand visibility.', NULL, 'rohit ', ARRAY[]::text[], 'https://www.instagram.com/reel/Dar0n3MREAF/?igsh=eGxnZHJ3dHM4dzRp', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/30zwpdoxazq-1785785233844.jpeg', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T19:13:53.977625+00:00', '2026-08-03T19:13:53.977625+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('e0430b3e-1223-4ea3-8f8d-f3aa182c1398', 'Yuvansh clinical  laboratory ', 'yuvansh-clinical-laboratory', 'marketing', 'Created promotional and informational videos for Yuvansh Clinic, focusing on healthcare services, patient awareness, and brand promotion. Edited content with smooth transitions, text animations, background music, and engaging visuals optimized for social media platforms.', NULL, 'yuvansh ', ARRAY[]::text[], 'https://www.instagram.com/reel/Da0o2QJR936/', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/xasrvfuz6bj-1785784814311.png', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T19:11:26.596655+00:00', '2026-08-03T19:11:26.596655+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('974e7a68-a32f-4935-bb98-5b5ce5dadff6', 'Sai communication', 'sai-communication', 'marketing', 'Created promotional and marketing videos for Sai Communication, focusing on product highlights, engaging visuals, smooth transitions, motion graphics, text animations, and social media optimization to increase brand awareness and customer engagement.', NULL, 'sai', ARRAY['gemini', 'chat gpt', 'flow', 'VN']::text[], 'https://www.instagram.com/reel/Da0BbsiRp_V/', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/yxrzp26fqjm-1785784839511.png', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T19:08:43.589951+00:00', '2026-08-03T19:08:43.589951+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('a43937f5-5977-4dbb-ab32-2109cebffc17', 'Rivaana ', 'rivaana', 'marketing', 'Produced creative promotional videos for Rivaana Fashion Boutique, highlighting trendy apparel, exclusive collections, and seasonal offers. Crafted visually engaging content with dynamic editing, motion graphics, music, and clean transitions to strengthen the boutique''s online presence and attract potential customers.', NULL, ' riva ', ARRAY['gemini', 'chatgpt', 'VN', 'Flow']::text[], 'https://www.instagram.com/reel/Dblt3eaB3hq/?igsh=ZjgwdXF6dXBobmFr', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/zl31k0p5vr9-1785785310003.png', NULL, NULL, true, true, NULL, 0, NULL, '2026-08-03T19:26:53.265723+00:00', '2026-08-03T19:26:53.265723+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('e6f1305d-3417-4540-bb61-2f050d8157c0', 'Spin the wheel ', 'spin-the-wheel', 'website', 'Developed an interactive Spin the Wheel web application that allows users to spin a customizable prize wheel and receive random rewards or outcomes. The project features smooth animations, responsive design, and an engaging user interface, making it suitable for promotions, giveaways, contests, and entertainment.', NULL, 'priti', ARRAY['next.ts']::text[], 'https://www.premiumstorekathua.shop/spin', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/bcpj4f7g5l-1785782718629.png', NULL, NULL, true, true, NULL, 0, NULL, '2026-08-03T18:13:47.597353+00:00', '2026-08-03T18:13:47.597353+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('da018c58-10df-4882-b2db-4b22a8091fc7', 'Shivangi stiches ', 'shivangi-stiches', 'website', 'Designed and developed a modern portfolio website for Shivangi Stiches to showcase custom stitching, designer outfits, alterations, and handcrafted creations. The website features an elegant, responsive design with a gallery, service section, about page, and contact form, helping customers explore the brand and connect easily.', NULL, 'Shivangi ', ARRAY['next.js', 'netlify']::text[], 'https://shivangistitches.netlify.app', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/r5ot0pyb6ta-1785780461711.png', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T18:08:47.252418+00:00', '2026-08-03T18:08:47.252418+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('8744e9db-66cc-45cc-9a8c-4cbc7eba721c', 'kathua fresh', 'kathua-fresh', 'app', 'Developed a user-friendly mobile application for ordering fresh fruits and vegetables. The app features easy product browsing, category-wise listings, a simple ordering process, and a responsive interface to provide a convenient and seamless shopping experience.', NULL, ' sahil ', ARRAY['NEXT.JS', 'CSS TAILWIND', 'RAZORPAY', 'SUPABASE']::text[], 'https://kathua-fresh-akhil.vercel.app', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/g5anj3qdf7-1785782125740.png', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T18:32:37.79633+00:00', '2026-08-03T18:32:37.79633+00:00');
INSERT INTO public.projects (id, title, slug, category, description, content, client_name, tech_stack, live_url, thumbnail_url, gallery_urls, video_url, is_featured, is_published, tags, sort_order, results, created_at, updated_at) VALUES ('5fb4b5cf-3436-401e-8b8e-cec4844b260e', 'Testimonial', 'testimonial', 'marketing', '', NULL, 'FAMOUS CLIENTS', ARRAY[]::text[], 'https://docs.google.com/spreadsheets/d/1NKHeH_O265m8QAzm0DL-Jx8qi-9t4Gf8MKtLUnDhutg/edit?gid=1789683222#gid=1789683222', 'https://vyvtpwlygyyjgfzmxvtd.supabase.co/storage/v1/object/public/media/uploads/zlae2zf19f-1785786336967.png', NULL, NULL, false, true, NULL, 0, NULL, '2026-08-03T19:46:08.697325+00:00', '2026-08-03T19:46:08.697325+00:00');

-- ===== SERVICES (7 rows) =====
DELETE FROM public.services;

INSERT INTO public.services (id, slug, title, tagline, description, icon, features, deliverables, process_steps, pricing_tiers, faqs, tech_used, timeline_min, timeline_max, is_published, sort_order, seo_title, seo_description) VALUES ('3c4ce4bb-4e7e-4fd1-ab39-f3b03a5a1fbf', 'landing-page', 'Landing Page', 'High-converting single page websites', 'A focused, high-converting one-page website designed to capture leads, sell a product, or promote an event.', 'Globe', NULL, ARRAY['1-page responsive site', 'SEO basics', 'Contact form', 'Fast loading speed']::text[], NULL, ARRAY['[object Object]']::text[], NULL, NULL, 3, 5, true, 1, NULL, NULL);
INSERT INTO public.services (id, slug, title, tagline, description, icon, features, deliverables, process_steps, pricing_tiers, faqs, tech_used, timeline_min, timeline_max, is_published, sort_order, seo_title, seo_description) VALUES ('85f7f983-4990-4604-a393-c95cbba2cf88', 'portfolio-website', 'Portfolio Website', 'Showcase your work professionally', 'A multi-page portfolio website with smooth animations, project showcases, contact forms, and blog integration.', 'Palette', NULL, ARRAY['Multi-page site', 'Animations', 'Contact form', 'Blog integration']::text[], NULL, ARRAY['[object Object]']::text[], NULL, NULL, 5, 7, true, 2, NULL, NULL);
INSERT INTO public.services (id, slug, title, tagline, description, icon, features, deliverables, process_steps, pricing_tiers, faqs, tech_used, timeline_min, timeline_max, is_published, sort_order, seo_title, seo_description) VALUES ('b54dbf4a-1ddd-4065-9a5c-d8e1ce408cce', 'business-website', 'Business Website', 'Complete digital presence for your brand', 'A full-scale business website with CMS, advanced SEO, analytics, and multiple pages tailored to your brand.', 'Briefcase', NULL, ARRAY['Full site', 'CMS integration', 'Advanced SEO', 'Analytics setup']::text[], NULL, ARRAY['[object Object]']::text[], NULL, NULL, 7, 14, true, 3, NULL, NULL);
INSERT INTO public.services (id, slug, title, tagline, description, icon, features, deliverables, process_steps, pricing_tiers, faqs, tech_used, timeline_min, timeline_max, is_published, sort_order, seo_title, seo_description) VALUES ('5e14cbe7-33aa-4eba-82c9-91e79dd51c15', 'app-development', 'App Development', 'Native and cross-platform mobile apps', 'Custom mobile application development using React Native or Web Apps with authentication and database integrations.', 'Smartphone', NULL, ARRAY['React Native / Web App', 'Authentication', 'Database integration', 'App store guidance']::text[], NULL, ARRAY['[object Object]']::text[], NULL, NULL, 15, 45, true, 4, NULL, NULL);
INSERT INTO public.services (id, slug, title, tagline, description, icon, features, deliverables, process_steps, pricing_tiers, faqs, tech_used, timeline_min, timeline_max, is_published, sort_order, seo_title, seo_description) VALUES ('c9901b98-3f65-4773-bd2f-3c151e01a1e3', 'video-editing', 'Video Editing', 'Cinematic editing for reels and ads', 'Professional video editing including color grading, captions, music syncing, and effects for social media and marketing.', 'Video', NULL, ARRAY['Color grading', 'Captions/Subtitles', 'Music synced reel', 'Motion graphics']::text[], NULL, ARRAY['[object Object]']::text[], NULL, NULL, 2, 3, true, 5, NULL, NULL);
INSERT INTO public.services (id, slug, title, tagline, description, icon, features, deliverables, process_steps, pricing_tiers, faqs, tech_used, timeline_min, timeline_max, is_published, sort_order, seo_title, seo_description) VALUES ('6e39449a-bb3f-4875-9323-59baf698cd80', 'branding', 'Branding Package', 'Complete brand identity design', 'A comprehensive branding package including logo design, color palettes, typography, and brand guidelines.', 'PenTool', NULL, ARRAY['Logo design', 'Color palette', 'Typography', 'Brand guidelines']::text[], NULL, ARRAY['[object Object]']::text[], NULL, NULL, 5, 7, true, 6, NULL, NULL);
INSERT INTO public.services (id, slug, title, tagline, description, icon, features, deliverables, process_steps, pricing_tiers, faqs, tech_used, timeline_min, timeline_max, is_published, sort_order, seo_title, seo_description) VALUES ('330b3e0e-c0f3-4640-834a-3410b06818ec', 'digital-marketing', 'Digital Marketing', 'Grow your audience and sales', 'Ongoing digital marketing services including social media posts, ad campaigns, and monthly analytics reporting.', 'Megaphone', NULL, ARRAY['Social posts', 'Ad campaigns', 'Analytics report', 'Strategy sessions']::text[], NULL, ARRAY['[object Object]']::text[], NULL, NULL, 30, 30, true, 7, NULL, NULL);

-- ===== TESTIMONIALS (5 rows) =====
DELETE FROM public.testimonials;

INSERT INTO public.testimonials (id, client_name, business_name, review, rating, avatar_url, video_url, service_type, is_featured, is_published, sort_order, created_at) VALUES ('dff5e457-04a5-4e5f-bfb8-2d755a89dbfc', 'Rahul Mehta', 'TechNova Solutions', 'Shivam Creates completely transformed our brand identity. The new website is not just beautiful, it’s lightning fast. We saw a 40% increase in lead conversions within the first month. Highly recommended for any ambitious startup!', 5, NULL, NULL, 'Web Development & Branding', true, true, 1, '2026-07-12T19:05:47.420796+00:00');
INSERT INTO public.testimonials (id, client_name, business_name, review, rating, avatar_url, video_url, service_type, is_featured, is_published, sort_order, created_at) VALUES ('3b2e7d85-7480-4f55-ba35-2804999dbe8f', 'Priya Sharma', 'The Artisan Café', 'I had zero technical knowledge, but Shivam made the entire process so simple. He built us an amazing business website and set up our digital marketing. The results have been incredible—our weekend footfall has doubled!', 5, NULL, NULL, 'Business Website & Marketing', true, true, 2, '2026-07-12T19:05:47.420796+00:00');
INSERT INTO public.testimonials (id, client_name, business_name, review, rating, avatar_url, video_url, service_type, is_featured, is_published, sort_order, created_at) VALUES ('1e734342-945a-4f2a-be70-fca4edb6608f', 'Alex K.', 'Elevate Fitness', 'Working with Shivam Creates was the best investment for my business. The mobile app he developed for my fitness coaching program is flawless. Fast communication, premium quality, and delivered exactly on time.', 5, NULL, NULL, 'App Development', true, true, 3, '2026-07-12T19:05:47.420796+00:00');
INSERT INTO public.testimonials (id, client_name, business_name, review, rating, avatar_url, video_url, service_type, is_featured, is_published, sort_order, created_at) VALUES ('d3f1dd07-ea40-43f0-85aa-79628b3e08f9', 'Rohan Desai', 'Desai Real Estate', 'The cinematic video editing and motion graphics provided by Shivam Creates are unmatched. Our property reels are getting thousands of views and generating high-quality leads. Exceptional work!', 5, NULL, NULL, 'Video Editing', false, true, 4, '2026-07-12T19:05:47.420796+00:00');
INSERT INTO public.testimonials (id, client_name, business_name, review, rating, avatar_url, video_url, service_type, is_featured, is_published, sort_order, created_at) VALUES ('041d1de9-4ea9-4eb4-9fbf-78c77307f71c', 'Aisha Singh', 'Aura Cosmetics', 'From the UI/UX design to the final launch, every step was handled with extreme professionalism. Our D2C store looks premium and feels so smooth. Shivam Creates is truly a world-class agency.', 5, NULL, NULL, 'UI/UX Design & Development', true, true, 5, '2026-07-12T19:05:47.420796+00:00');

